name: Coding Standards 

on:
  pull_request:
    branches: [ "master" ]
jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tidy-checks: -boost, -bugprone, -performance, -portability, -modernize, -clang-anlayzer, -cppcoreguidelines
          files-changed-only: false
          extra-args: -std=c++17 -I ./include
      - name: Failed coding standard check
        if: steps.linter.outputs.check-failed > 0
        run: exit 1   